# Generated by Django 4.2.16 on 2025-03-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medication", "0006_remove_medication_stopped_by_datetime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medication",
            name="duration",
        ),
        migrations.AddField(
            model_name="medication",
            name="stopped_by_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
