# Generated by Django 5.1.6 on 2025-02-06 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "image",
                    models.ImageField(default="default.jpeg", upload_to="profile"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                (
                    "therapy",
                    models.CharField(
                        choices=[("insulin", "Insulin"), ("Tablets", "Tablets")],
                        max_length=10,
                    ),
                ),
                ("weight", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                (
                    "diabetes_type",
                    models.CharField(
                        choices=[
                            ("Type 1", "Type 1"),
                            ("Type 2", "Type 2"),
                            ("Pre Diabetic", "Pre Diabetic"),
                            ("genetic predisposition", "genetic predisposition"),
                            ("Normal", "Normal"),
                        ],
                        max_length=22,
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
