# Generated by Django 4.2.16 on 2025-02-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="daily_calorie_goal",
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=7),
        ),
    ]
